### ISSUE TITLE
```npm run start``` failed to compile 

### ISSUE THREAD

**Issue by jzhou59** [AlanBinu007/ReactJs-SpringBoot-MySql#18]
Hi 😄 , I am trying to run ```npm run start``` under folder ``` Springboot-ReactJS-Ecommerce-Shopping-FrontEnd ```, while encountering ```failed to compile``` 😕 . How could I fix this?

![image](https://user-images.githubusercontent.com/28994988/147520750-c2183117-6419-4ad2-a483-e9f295dc4b90.png)

![image](https://user-images.githubusercontent.com/28994988/147520778-fd9d6289-f91a-496d-b318-34e5faa6cbff.png)

**Comment by AlanBinu007** [comment]
Hi, Thanks for visiting me.
Actually i teaches some of my junior students, so that is a sample template for them to beign with.
I will upload the full code later on.
Mean while you can look to the same application :  https://github.com/AlanBinu007/E_Commerce_App_ReactJs

I hope this helps
